### ISSUE TITLE
Registering to: subscription.rhsm.redhat.com:443/subscription fails

### ISSUE THREAD

**Issue by redmark-alt** [ocp-power-automation/ocs-upi-kvm#17]
Something in the install changes the host (may be the dnsmasq) and the following steps fails. The host was a clean installed 8.3 host.

module.prepare.null_resource.bastion_init (remote-exec): Registering to: subscription.rhsm.redhat.com:443/subscription

I finally just modified the /etc/hosts file to get past this.

10.4.204.72 subscription.rhsm.redhat.com

**Comment by redmark-alt** [comment]
Same issue with cdn.redhat.com

**Comment by lukebrowning** [comment]
Should be fixed with https://github.com/ocp-power-automation/ocs-upi-kvm/commit/a322d9c9cf87e4bf806355800cf6cfcf4d261fce
