### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xnf50bcd/cryptography/

### ISSUE THREAD

**Issue by redmark-alt** [ocp-power-automation/ocs-upi-kvm#18]
Clean Red Hat 8.3 host. The install script continues to fail with the following error.

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xnf50bcd/cryptography/

I tried running the following command and then run the install again but no luck.

"alternatives --set python /usr/bin/python3"

I'm using an 8.3 bastion image which seems to be the issue here. Downlevel python????

**Comment by lukebrowning** [comment]
Should be fixed with https://github.com/ocp-power-automation/ocs-upi-kvm/commit/a322d9c9cf87e4bf806355800cf6cfcf4d261fce
