### ISSUE TITLE
FAILED - RETRYING: Approve Worker CSRs (1 retries left).

### ISSUE THREAD

**Issue by redmark-alt** [ocp-power-automation/ocs-upi-kvm#19]
Each install attempt end with the same error here. Host KVM is RHEL 8.3 libvert 6.0 I also tried RHCOS 4.6.1 but no luck.

export BASTION_IMAGE=rhel-8.2-update-2-ppc64le-kvm.qcow2
export OCP_VERSION=4.6
export RHCOS_RELEASE=4.6.8

module.install.null_resource.install (remote-exec): FAILED - RETRYING: Approve Worker CSRs (1 retries left).
module.install.null_resource.install: Still creating... [2h16m1s elapsed]
module.install.null_resource.install: Still creating... [2h16m11s elapsed]
module.install.null_resource.install: Still creating... [2h16m21s elapsed]
module.install.null_resource.install: Still creating... [2h16m31s elapsed]
module.install.null_resource.install: Still creating... [2h16m41s elapsed]
module.install.null_resource.install: Still creating... [2h16m51s elapsed]
module.install.null_resource.install: Still creating... [2h17m1s elapsed]
module.install.null_resource.install: Still creating... [2h17m11s elapsed]
module.install.null_resource.install (remote-exec): fatal: [localhost]: FAILED! => {"attempts": 30, "changed": true, "cmd": "oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs -r oc adm certificate approve\n", "delta": "0:00:12.160202", "end": "2020-12-15 19:22:51.134883", "rc": 0, "start": "2020-12-15 19:22:38.974681", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

module.install.null_resource.install (remote-exec): PLAY RECAP *********************************************************************
module.install.null_resource.install (remote-exec): 192.168.88.21              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.22              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.23              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.24              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.25              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.26              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.27              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.28              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.29              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.3               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.30              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.4               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.5               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): 192.168.88.6               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
module.install.null_resource.install (remote-exec): localhost                  : ok=31   changed=24   unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

Error: error executing "/tmp/terraform_1332708893.sh": Process exited with status 2

**Comment by lukebrowning** [comment]
Should be fixed with https://github.com/ocp-power-automation/ocs-upi-kvm/commit/a322d9c9cf87e4bf806355800cf6cfcf4d261fce
