### ISSUE TITLE
ocp 4.6.5 is not part of the "stable" packages

### ISSUE THREAD

**Issue by redmark-alt** [ocp-power-automation/ocs-upi-kvm#22]
I recommend that the default be changed to 4.6.8..  I had to switch to "candidate" to move up to 4.6.8. I had to switch to "candidate" to move up to 4.6.8.... Once we get to the 4.6.8 the version is in the "stable" packages. 

OCP_RELEASE="4.6.5"		# Latest release of OCP 4.6 at this time

![image](https://user-images.githubusercontent.com/55297908/105732511-85893d00-5efe-11eb-9d21-9bde68e9731c.png)

![image](https://user-images.githubusercontent.com/55297908/105732329-54a90800-5efe-11eb-8594-a94a82f4b812.png)

**Comment by lukebrowning** [comment]
done
