### ISSUE TITLE
Is the haproxy file correct.

### ISSUE THREAD

**Issue by redmark-alt** [ocp-power-automation/ocs-upi-kvm#24]
Note the section here is it correct?

frontend openshift-configserver
    bind *:22623
    default_backend openshift-configserver
    mode tcp
    option tcplog
#---------------------------------------------------------------------
#Backend openshift config server
#---------------------------------------------------------------------
backend openshift-configserver
    balance     roundrobin
    mode        tcp
    server master-0 192.168.88.4:**6443** check.  <<< Should it be 22623
    server master-1 192.168.88.5:**6443** check   <<< Should it be 22623
    server master-2 192.168.88.6:**6443** check  <<< Should it be 22623
    server bootstrap 192.168.88.3:**6443** check  <<< Should it be 22623

Note the link here describes the haproxy file.

https://www.openshift.com/blog/openshift-4-bare-metal-install-quickstart

**Comment by lukebrowning** [comment]
Those values haven't changed.   We are seeing the same failure.   I asked @manojnkumar on our internal slack channel

**Comment by lukebrowning** [comment]
@redmark-alt If you can figure it out, please submit a pull request.

**Comment by lukebrowning** [comment]
@redmark-alt Does that change solve the problem for you?

**Comment by redmark-alt** [comment]
@lukebrowning We were seeing sporadic events with port `22623` in body of the message. Searching I found several hits about the port needing to be open.

https://www.openshift.com/blog/openshift-4-bare-metal-install-quickstart
