### ISSUE TITLE
Package wipe is not found on RHEL8.3

### ISSUE THREAD

**Issue by mgiessing** [ocp-power-automation/ocs-upi-kvm#62]
When I'm following this guide, the package wipe cannot be installed as shown below:

```
[...]
Package python3-libvirt-6.0.0-1.module+el8.3.0+6423+e4cb6418.ppc64le is already installed.
No match for argument: wipe
Error: Unable to find a match: wipe
[...]
```

I executed following on an AC922:

```
dnf install git -y
git clone https://github.com/ocp-power-automation/ocs-upi-kvm.git && cd ocs-upi-kvm
git submodule update --init
export RHID_USERNAME=<user>
export RHID_PASSWORD=<password>
vi /root/pull-secret.txt
cd scripts/
./create-ocp.sh 
```

Thanks!

**Comment by lukebrowning** [comment]
I am retiring at the end of the month, so I will leave this to the team to fix.  

Marvin, You can workaroung this problem by doing:

1.  Download wipe rpm from somewhere else and install it.   This step is only necessary if you intend to use physical data disk(s) as opposed to qcow2 files for OVCS data disks.   
2.  Edit the script and remove wipe from the list of packages to be installed

Good Luck, Luke

**Comment by lukebrowning** [comment]
http://rpmfind.net/linux/rpm2html/search.php?query=wipe

Use the latest fedora package

**Comment by lukebrowning** [comment]
This is an older version that I had installed on my test server

[luke@nx144-ahv ~]$ sudo yum info wipe.ppc64le
Updating Subscription Management repositories.
Last metadata expiration check: 1:16:08 ago on Thu 29 Jul 2021 04:36:47 PM CDT.
Installed Packages
Name         : wipe
Version      : 2.3.1
Release      : 18.1
Architecture : ppc64le
Size         : 99 k
Source       : wipe-2.3.1-18.1.src.rpm
Repository   : @System
From repo    : @commandline
Summary      : Secure Erasure of Data
URL          : http://wipe.sourceforge.net/
License      : GPL-2.0-or-later
Description  : Wipe is a tool that attempts to effectively degauses the surface of
             : a hard disk, making it virtually impossible to retrieve the data
             : that was stored on it. This tool is designed to make sure secure
             : data that is erased from a hard drive is unrecoverable.

**Comment by mgiessing** [comment]
Yes, perfect I just edited the script to make it work as I'm working with qcow2 :-)
