### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by lukebrowning** [ocp-power-automation/ocs-upi-kvm#69]
Hi @aditidukle 

Note that when you change src/powervs there may be new ocp4-upi-powervs parameters that need to be specified.   This would be done by setting environment variables [here](https://github.com/ocp-power-automation/ocs-upi-kvm/blob/master/scripts/helper/powervs/parameters.sh) and [here](https://github.com/ocp-power-automation/ocs-upi-kvm/blob/master/files/powervs/site.tfvars.in).   These parameters are specific to ocp4-upi-powervs/powervm/kvm release branches.   In this case, you would need to create release branches in the path to the site.tfvars.in file such as files/powervs/<OCP_RELEASE>/site.tfvars.in.   To maintain support for OCP 4.4, you would simply duplicate the OCP 4.5 site file for OCP 4.4, since the underlying code checks out the OCP 4.5 branch for 4.4.    

Good luck and please close this git issue whenever you like.

Luke 
lukebrowning@yahoo.com

**Comment by aditidukle** [comment]
Hi @lukebrowning 
I had checked if new parameters were created in powervs repo in the following files by comparing older branches:
- https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/variables.tf 
- https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/ocp.tf
- https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/var.tfvars
We don't have any new parameters being introduced in ocp4-upi-powervs repo
