### ISSUE TITLE
OCS 4.9 client version and RHCOS version are down level

### ISSUE THREAD

**Issue by lukebrowning** [ocp-power-automation/ocs-upi-kvm#90]
I am not sure if these are issues.  You may be working around them by setting environment variables, but I thought I would mention them just in case you weren't aware.   

Luke

---

rhcos 4.9.0 is officially released now which affects the version of the ocp client installer that you use.   You are using a down level ocp installer.   The ocp client installer is set to use 4.9.0 while the latest stable version is 4.9.5.   

In addtion, the default powervs 4.9 rhcos image is 5+ weeks old based on the date in its file name "rhcos-49-09072021", but perhaps you are overwriting the environment variable.   rhcos-49-09072021 equates to 4.9.0-rc.0 and there were many release candidates.

The key question here is what is Redhat's stance on minimum OCP version for OCS 4.9.   Is it OCP 4.9.0 or 4.9.5 or 4.9.7?

Also ocs 4.8 is 2.5 months downlevel which may provide a better base for upgrade testing.  

Notes:

In scripts/helper/create-cluster.sh:

4.8)
                **OCP_RELEASE="4.8.5"**
                RHCOS_VERSION="4.8"
                if [ -z "$RHCOS_RELEASE" ]; then
                         **RHCOS_RELEASE="4.8.2"                   # Latest release of RHCOS 4.8 at this time**
                fi
               RHCOS_SUFFIX="-$RHCOS_RELEASE"
               ;;
4.9)
               **OCP_RELEASE="4.9.0"**
               **RHCOS_VERSION="4.8"**
               **unset RHCOS_RELEASE**
               RHCOS_SUFFIX="-$RHCOS_VERSION"
               ;;		
*)
               echo "Invalid OCP_VERSION=$OCP_VERSION.  Supported versions are 4.4 - 4.9"
               exit 1
esac

if [ -n "$RHCOS_RELEASE" ]; then
               export OCP_INSTALLER_SUBPATH="ocp/stable-$OCP_VERSION"
elif [ -n "$OCP_RELEASE" ]; then
               export OCP_INSTALLER_SUBPATH="ocp/$OCP_RELEASE"
else
               export OCP_INSTALLER_SUBPATH="ocp-dev-preview/latest-$OCP_VERSION"
fi

You are probably getting the wrong path above for the ocp installer version.   OCP 4.9 GA'd long ago.  

In scripts/helper/powervs/parameters.sh:

4.8)
              **export RHCOS_IMAGE=${RHCOS_IMAGE:="rhcos-48-07222021"}**
              export OCP_PROJECT_COMMIT="origin/release-4.8"
              ;;
4.9)
              **export RHCOS_IMAGE=${RHCOS_IMAGE:="rhcos-49-09072021"}**
	      ;;	
esac

Note the 4.8 image is 3 months old.   The rhcos image is 5+ weeks old.

**Comment by lukebrowning** [comment]
Actually, you are getting the ocp/4.9.0 version of the installer which is two weeks behind the ocp-stable-4.9 version, but the question is whether you want 4.9.0 or 4.9.5 or 4.9.7.   I believe with RHCOS_RELEASE not being set, you are getting the 4.8 rhcos image for kvm.

**Comment by aditidukle** [comment]
Hi @lukebrowning. The following change was done 3 weeks ago as the stable-4.9 was not available at that time. 
4.9)
OCP_RELEASE="4.9.0"
RHCOS_VERSION="4.8"
unset RHCOS_RELEASE
RHCOS_SUFFIX="-$RHCOS_VERSION"
;;

Have now raised a PR to update all the versions. Thanks

**Comment by lukebrowning** [comment]
Looks good.  I assume that a new powervs rhcos 4.9 image is in the works...

Luke
